---

- name: set role variables, if necessary
  import_tasks: setup-service-variable.yml

- name: use YUM installation
  import_tasks: setup-rhel.yml
  when: ansible_os_family == 'RedHat'

- name: use APT installation
  import_tasks: setup-ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: setup agent
  import_tasks: td-agent.yml

- name: setup agent plugins
  import_tasks: plugins.yml

- name: setup agent configuration
  import_tasks: templates.yml  