---

- name: Remove config.d folder
  file: path=/etc/td-agent/config.d state=absent
  notify: restart td-agent

- name: Create config.d folder
  file: path=/etc/td-agent/config.d state=directory mode=0775

- name: Configure td-agent.conf
  template:
    src: td-agent.j2
    dest: /etc/td-agent/td-agent.conf
    owner: td-agent
    group: td-agent
