---
driver:
  name: ec2
  use_sudo: false
  privileged: true
  #aws_ssh_key_id: id_rsa-aws
  region: us-east-2
  #iam_profile_name: test-kitchen
  instance_type: t2.micro
  associate_public_ip: true  

transport:
  #ssh_key: id_rsa-aws
  connection_timeout: 10
  connection_retries: 2


provisioner:
  name: ansible_playbook
  roles_path: fluentd/
  #requirements_path: requirements.yml
  hosts: all
  playbook: test.yml
  ansible_verbose: true
  ansible_verbosity: 4
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  require_ansible_omnibus: false
  ansible_connection: ssh
  require_chef_for_busser: false
  require_ruby_for_busser: false

platforms:
  - name: ubuntu-14.04
    transport:
      username: ubuntu    
  - name: ubuntu-16.04
    transport:
      username: ubuntu  
  - name: centos-7
    transport:
      username: centos    

suites:
  - name: test
    

#verifier:
#  name: inspec
#  sudo: true
#  inspec_tests:
#    - https://github.com/dev-sec/linux-baseline