---
- hosts: all
  become: true
  roles:
    - fluentd/kernel
    - fluentd/limits
    - fluentd/td-agent
  #vars_files:
  #  - '/fluentd/td-agent/defaults/main.yml'
  vars:
    tdagent_version: 2.3.4
    tdagent_plugins:
      - fluent-plugin-multiprocess
      - fluent-plugin-anonymizer
      - fluent-plugin-forest
      - fluent-plugin-record-reformer
      #- fluent-plugin-elasticsearch
      - fluent-plugin-kinesis 
    #tdagent_plugins_versions:
    #  prometheus:
    #    name: fluent-plugin-prometheus
    #    version: 0.1.2
    #  flowcounter:
    #    name: fluent-plugin-flowcounter
    #    version: 0.4.1

    # copy verbatim
    #tdagent_conf_copy: "/fluentd/td-agent/files/td-agent.conf"

    # copy through Ansible's template system
    # tdagent_conf_template: "fluentd/td-agent/templates/td-agent.conf.j2"

    #tdagent_conf_others:
    #  prometheus_metrics:
    #    src:  test/prometheus.conf.j2
    #    dest: prometheus.conf