- name: install libselinux-python binary for Ansible to work
  yum:
    name: libselinux-python
    state: present

- name: add GPG key from Treasure Data, Inc
  rpm_key: key=https://packages.treasuredata.com/GPG-KEY-td-agent validate_certs=no state=present

- name: add official repository
  copy: src=../files/td.repo dest=/etc/yum.repos.d/td.repo

- name: install td-agent
  yum: name=td-agent  update_cache=yes  state=present
  when: tdagent_version is not defined

- name: install td-agent
  yum: name="td-agent-{{ tdagent_version }}*"  update_cache=yes  state=present
  when: tdagent_version is defined

- name: install gcc and libcurlXXX for compiling plugins
  yum:
    name:
     - gcc
     - libcurl
     - libcurl-devel
    state: present
  when: tdagent_plugins is defined or tdagent_plugins_versions is defined

- name: set INIT status and start
  service: name=td-agent state=started enabled=yes
  when: tdagent_use_service|bool

- name: set INIT status (SysV style)
  service: name=td-agent state=present
  when: not tdagent_use_service|bool

#- name: set INIT status (SysV style)
#  action: shell chkconfig --add td-agent
#  action: shell chkconfig --level 345 td-agent on